# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for bun in api/
  - package-ecosystem: "bun"
    directory: "/api"
    schedule:
      interval: "monthly"
    ignore:
      # ESM only in 3.x
      - dependency-name: "@thream/socketio-jwt"
        versions: ["3.x"]
      # Puppeteer wasn't building for Node 18, should be able to remove this when we go Node 20
      - dependency-name: "puppeteer"
        versions: ["23.x"]
      # Until we move to Express 5, we need to stick with the types for Express 4
      - dependency-name: "@types/express"
        versions: ["5.x"]
    # Group all dependencies into one PR for backend.
    # Note: security PRs will still be their own for visibility.
    groups:
      api:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for bun in demo/
  - package-ecosystem: "bun"
    directory: "/demo"
    schedule:
      interval: "monthly"
    groups:
      demo:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for bun in ui/
  - package-ecosystem: "bun"
    directory: "/ui"
    schedule:
      interval: "monthly"
    groups:
      ui:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for bun in backend-example/
  - package-ecosystem: "bun"
    directory: "/backend-example"
    schedule:
      interval: "monthly"
    groups:
      backend-example:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for bun in frontend-example/
  - package-ecosystem: "bun"
    directory: "/frontend-example"
    schedule:
      interval: "monthly"
    groups:
      frontend-example:
        applies-to: version-updates
        patterns:
          - "*"
  # Maintain dependencies for bun in rtk/
  - package-ecosystem: "bun"
    directory: "/rtk"
    schedule:
      interval: "monthly"
    groups:
      rtk:
        applies-to: version-updates
        patterns:
          - "*"
